name: Build OBS Plugin

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      # 1. Repositoryni klonlash
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. CMake'ni sozlash va yig'ish
      - name: Set up CMake
        uses: lukka/get-cmake@v3

      - name: Build Plugin
        run: |
          mkdir build
          cd build
          cmake .. -G "Visual Studio 16 2019" -A x64
          cmake --build . --config Release

      # 3. Yig'ilgan fayllarni saqlash
      - name: Upload Plugin Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: obs-plugin-build
          path: build/Release
